# Generated by Django 5.2 on 2025-05-04 14:53

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="date_published",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 4, 14, 53, 15, 100252, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата публикации",
            ),
        ),
    ]
