# Generated by Django 5.2 on 2025-05-04 14:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_blog_date_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="date_published",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата публикации"
            ),
        ),
    ]
